server:
  port: 8901

rate-limiter:
  limiters:
    basic:
      limit: 10
      unit: MINUTES
    test:
      limit: 5
      unit: SECONDS

logging:
  level:
    ru:
      openblocks:
        ratelimiter:
          service:
            RateLimiterService: INFO